version: '2'
services:
    furymusic-app:
        image: furymusic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://furymusic-mysql:3306/furymusic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    furymusic-mysql:
        extends:
            file: mysql.yml
            service: furymusic-mysql
